<? php
echo '<html>';
echo '<head>';
echo '<title>HOME</title>';
echo '<link rel="stylesheet" type = "text/css" href = "css/style.css"/>';
echo '</head>';
echo '<body>';
echo '';
echo '<div class = "header">';
echo '<div class = "navi">';
echo '<a href = "index.html"><font color = "black"> HOME</font></a>';
echo '<a href = "01.html"><font color = "black"> ABOUT US</font></a>';
echo '<a href = "02.html"><font color = "black"> PORTFOLIO</font></a>';
echo '<a href = "03.html"><font color = "black"> GALLERY</font></a>';
echo '<a href = "04.html"><font color = "black"> CLIENTS</font></a>';
echo '<a href = "05.html"><font color = "black"> CONTACT US</font></a>';
echo '</div>';
echo '<br>';
echo '<br>';
echo '<div class = "body1">';
echo '';
echo '<br>';
echo '<h1 align = "center"> HOME</h1>';
echo '<p align = "center"><font size = "4">We’re not just passionate purveyors of coffee, but everything else that goes with a full and rewarding coffeehouse experience. We also offer a selection of fine pastries and other delectable treats to please the taste buds.';
echo '</font></p>';
echo '<p align = "center"><font size = "4">And the music you hear in store is chosen for its artistry and appeal.It’s not unusual to see people coming to JAVA to chat, meet up or even work. We’re a neighborhood gathering place, a part of the daily routine – and we couldn’t be happier about it.';
echo '</font></p>';
echo '<p align = "center"><font size = "4">Get to know us and you’ll see: we are so much more than what we brew. We make sure everything we do is through the lens of humanity – from our commitment to the highest quality coffee in the world, to the way we engage with our customers and communities to do business responsibly.';
echo '</font></p>';
echo '</div>';
echo '<div class = "clear">';
echo '</div>';
echo '</div>';
echo '<br>';
echo '<div class = "body2">';
echo '<div class = "left">';
echo '<h1><font size = "5"> NEWS AND EVENTS</font><h1>';
echo '<p align = "left" ><font size = "4" face = "Times New Roman"> February 1, 2019</font></p>';
echo '<p align = "center" ><font size = "4" > JAVA CELEBRATES VALENTINE'S</font></p>';
echo '<p align = "center" ><font size = "3" face = "Times New Roman" > To kick off the love month this February, JAVA prepared promos and discount for customers visiting our store starting February 1-14, 2019</font></p>';
echo '<p align = "left" ><font size = "4" face = "Times New Roman"> January 31, 2018</font></p>';
echo '<p align = "center" ><font size = "4" > JAVA 2018: MEMORIES</font></p>';
echo '<p align = "center" ><font size = "3" face = "Times New Roman" > A new scent, Charity event 2018, Brewing sessions..<br>';
echo 'See the photos that reminds us of 2018 </font></p>';
echo '</div>';
echo '<div class = "clear"></div>';
echo '</div>';
echo '<div class = "footer">';
echo '<br>';
echo '<p><font size = "4"> JAVA </font></p>';
echo '<p><font size = "2">© 2019 JAVA Coffee Company. All rights reserved. </font></p>';
echo '';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>
